apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: client-with-mesher
spec:
  selector:
    matchLabels:
      app: client-with-mesher
  template:
    metadata:
      annotations:
        sidecar.mesher.io/inject: "yes"
        sidecar.mesher.io/discoveryType: "sc"
        sidecar.istio.io/inject: "false"
      labels:
        app: client-with-mesher
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: worker1
                operator: In
                values:
                - "true"
      containers:
        - name: client-with-mesher
          image: xiaoliang/client-go:latest
          imagePullPolicy: IfNotPresent
          env:
          - name: TARGET
            value: http://server-with-mesher:9999
          - name: http_proxy
            value: http://127.0.0.1:30101/
          ports:
            - containerPort: 9000

---
apiVersion: v1
kind: Service
apiVersion: v1
metadata:
  name: client-with-mesher
spec:
  selector:
    app: client-with-mesher
  ports:
  - protocol: TCP
    name: http
    port: 9000
    nodePort: 9000
  type: NodePort
